/-
Kernel-checked data for the lower bound `ℰ ≥ 0.47913…` (`Families.Certificate.Ecal`).

`loopA (P-1) 2 S` runs over `k = 2, …, P = 50000` and multiplies the running integer `L` (initially
`S = 10^20`) by `(k³-k-1)/k³ = 1 - k⁻² - k⁻³`, rounded **down**, unless trial division by an entry
`d` of `smallDivs` with `2 ≤ d < k` exhibits `k` as composite. Soundness needs no primality of the
`smallDivs` (only `2 ≤ d < k`, `d ∣ k`), and no completeness: keeping a composite only lowers the
product. Generated by a small script (not included); checked by `decide +kernel`
(no `native_decide`). This file imports nothing.
-/

namespace Families.EcalData

/-- Trial divisors (the primes `≤ 223`; `223² > 50000`). -/
def smallDivs : List Nat := [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223]

/-- `true` only if some `d ∈ smallDivs` with `2 ≤ d < k` divides `k` (so `k` is composite). -/
def witness (k : Nat) : Bool :=
  smallDivs.any (fun d => decide (2 ≤ d) && decide (d < k) && k % d == 0)

/-- One step: `L ↦ ⌊L (k³-k-1)/k³⌋` unless `k` is certified composite. -/
def step (k L : Nat) : Nat := if witness k = true then L else L * (k ^ 3 - k - 1) / k ^ 3

/-- Run `step` for `k, k+1, …, k+n-1`. -/
def loopA : Nat → Nat → Nat → Nat
  | 0, _, L => L
  | n + 1, k, L => loopA n (k + 1) (step k L)

/-- The final integer: `L/S ≤ ∏_{p ≤ 50000} (1 - p⁻² - p⁻³)` with `S = 10^20`. -/
def ecalL : Nat := 47914615903693286585

theorem loopA_eq : loopA 49999 2 100000000000000000000 = ecalL := by decide +kernel

end Families.EcalData
