/-
Kernel-checked data for the upper bound `B < 3.73` (`Families.Phase1.B.BconstCert`).

`loopP (P-1) 2 (J, S)` runs over `k = 2, …, P = 100000` with state `(m, L)`: `m ← newton3 k m`
(three Newton steps for `√(kJ²)`), and `L` (initially `S = 10^20`) is multiplied by the rational upper bound
`bnum/bden = 1 + (kJ² + m²)/(2mJk(k−1)) + 1/(k²(k−1)) ≥ 1 + k^{-1/2}/(k−1) + 1/(k²(k−1))`
(AM–GM: `k^{-1/2} ≤ (kJ² + m²)/(2mJk)` for every `m ≥ 1`; soundness does not depend on `m`), rounded
**up**, unless trial division by an entry `d` of `smallDivs` with `2 ≤ d < k` exhibits `k` as composite.
Keeping an uncertified composite only enlarges the product (all factors are `≥ 1`). The run is split into
5 chunks (`chunk0`, …) with explicit intermediate states, each checked by `decide +kernel`
(no `native_decide`). Generated by `gen_bconst2.py` (in this directory). Imports nothing.
-/

namespace Families.BconstData

/-- Trial divisors (the primes `≤ 316`; `317² > 100000`). -/
def smallDivs : List Nat := [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313]

/-- `true` only if some `d ∈ smallDivs` with `2 ≤ d < k` divides `k` (so `k` is composite). -/
def witness (k : Nat) : Bool :=
  smallDivs.any (fun d => decide (2 ≤ d) && decide (d < k) && k % d == 0)

/-- The scale of the square-root approximation. -/
def J : Nat := 10000

/-- One Newton step for `√(k J²)`. -/
def newton (k m : Nat) : Nat := (m + k * J * J / m) / 2

def newton3 (k m : Nat) : Nat := newton k (newton k (newton k m))

def bnum (k m : Nat) : Nat := 2 * m * J * k * k * (k - 1) + (k * J * J + m * m) * k + 2 * m * J

def bden (k m : Nat) : Nat := 2 * m * J * k * k * (k - 1)

/-- One step on `L`: `L ↦ ⌈L · bnum/bden⌉` unless `k` is certified composite (`2L` if `m = 0`). -/
def step (k m L : Nat) : Nat :=
  if witness k = true then L else if m = 0 then 2 * L else (L * bnum k m + bden k m - 1) / bden k m

/-- One step on the state `(m, L)`. -/
def stepP (k : Nat) (s : Nat × Nat) : Nat × Nat := (newton3 k s.1, step k (newton3 k s.1) s.2)

/-- Run `stepP` for `k, k+1, …, k+n-1`. -/
def loopP : Nat → Nat → Nat × Nat → Nat × Nat
  | 0, _, s => s
  | n + 1, k, s => loopP n (k + 1) (stepP k s)

/-- The final integer: `∏_{p ≤ 100000} bfac p ≤ bL/S`, `S = 10^20`. -/
def bL : Nat := 372363293253511795112

/-- The final `m`. -/
def bM : Nat := 3162277

theorem chunk0 : loopP 20000 2 (10000, 100000000000000000000) = (1414248, 372088715217008841495) := by
  decide +kernel

theorem chunk1 : loopP 20000 20002 (1414248, 372088715217008841495) = (2000024, 372239305347743028859) := by
  decide +kernel

theorem chunk2 : loopP 20000 40002 (2000024, 372239305347743028859) = (2449510, 372302662656242232973) := by
  decide +kernel

theorem chunk3 : loopP 20000 60002 (2449510, 372302662656242232973) = (2828444, 372338891815241806403) := by
  decide +kernel

theorem chunk4 : loopP 19999 80002 (2828444, 372338891815241806403) = (3162277, 372363293253511795112) := by
  decide +kernel

end Families.BconstData
