/-
# The certificate `B < 3.73` (`lem:fS`(iii); Table `tab:constants`)

`Bconst_lt : Bconst < 3.73`, hence `lemfS_proof : lemfS_Statement`.

`B = ∏_p bfac(p)`, `bfac(p) = 1 + p^{−1/2}/(p−1) + 1/(p²(p−1))`, `B = 3.7256…` (0.12% below `3.73`).
* **Head** (`p ≤ P = 10⁵`): the kernel-checked integer loop `BconstData.loopP` (five chunks) gives
  `∏_{p ≤ P} bfac(p) ≤ bL/S` (`head_le`), using the AM–GM bound
  `p^{−1/2} ≤ (pJ² + m²)/(2mJp)` (any `m ≥ 1`) and trial division by the primes `≤ 316`.
* **Tail** (`p > P`): `bfac(p) − 1 ≤ (1 + 3/P) p^{−3/2}` and, by Abel summation against
  Chebyshev's `θ(n) ≤ n log 4` (`Chebyshev.theta_le_log4_mul_x`),
  `∑_{P < p ≤ N} p^{−3/2} ≤ 3 log 4 · (P+1)^{−1/2}/log(P+1)` (`sum_prime_rpow_tail_le`).
* So `log B ≤ log(bL/S) + T`, `T ≤ 0.00119`, and `B ≤ (bL/S)/(1 − T) < 3.7281 < 3.73`.

The data file `BconstData.lean` is generated by the script `gen_bconst2.py` (in this directory);
it re-runs the same loop in Python with Lean's `Nat` semantics.
-/
import Families.Phase1.B.FSAssemble
import Families.Phase1.B.BconstData

noncomputable section

open scoped BigOperators
open Finset

namespace Families.Phase1.B

open Families BconstData

/-! ### Soundness of the kernel loop -/

lemma witness_sound {k : ℕ} (h : witness k = true) : ¬ k.Prime := by
  unfold witness at h
  rw [List.any_eq_true] at h
  obtain ⟨d, -, hd⟩ := h
  simp only [Bool.and_eq_true, decide_eq_true_eq, beq_iff_eq] at hd
  exact Nat.not_prime_of_dvd_of_lt (Nat.dvd_of_mod_eq_zero hd.2) hd.1.1 hd.1.2

/-- `bfac k ≥ 1` for `k ≥ 2` (not only primes). -/
lemma one_le_bfac' {k : ℕ} (hk : 2 ≤ k) : 1 ≤ bfac k := by
  have h2 : (2 : ℝ) ≤ k := by exact_mod_cast hk
  unfold bfac
  have : 0 ≤ (k : ℝ) ^ (-(1 / 2 : ℝ)) / ((k : ℝ) - 1) :=
    div_nonneg (Real.rpow_nonneg (by linarith) _) (by linarith)
  have : 0 ≤ (k : ℝ)⁻¹ / ((k : ℝ) * ((k : ℝ) - 1)) :=
    div_nonneg (inv_nonneg.mpr (by linarith)) (mul_nonneg (by linarith) (by linarith))
  linarith

/-- `bfac k ≤ 2` for `k ≥ 2`. -/
lemma bfac_le_two {k : ℕ} (hk : 2 ≤ k) : bfac k ≤ 2 := by
  have h2 : (2 : ℝ) ≤ k := by exact_mod_cast hk
  have hk0 : (0 : ℝ) < k := by linarith
  unfold bfac
  have t2 : (k : ℝ)⁻¹ / ((k : ℝ) * ((k : ℝ) - 1)) ≤ 1 / 4 := by
    have hi : (k : ℝ)⁻¹ ≤ 1 / 2 := by rw [inv_le_comm₀ hk0 (by norm_num)]; linarith
    have hd : (2 : ℝ) ≤ (k : ℝ) * ((k : ℝ) - 1) := by nlinarith
    calc (k : ℝ)⁻¹ / ((k : ℝ) * ((k : ℝ) - 1)) ≤ (1 / 2) / 2 :=
          div_le_div₀ (by norm_num) hi (by norm_num) hd
      _ = 1 / 4 := by norm_num
  -- `k^{-1/2}/(k−1) ≤ k^{-1/2} ≤ 2^{-1/2} < 3/4`
  have t1' : (k : ℝ) ^ (-(1 / 2 : ℝ)) / ((k : ℝ) - 1) ≤ 3 / 4 := by
    have hs : (k : ℝ) ^ (-(1 / 2 : ℝ)) ≤ (2 : ℝ) ^ (-(1 / 2 : ℝ)) :=
      Real.rpow_le_rpow_of_nonpos (by norm_num) h2 (by norm_num)
    have h2s : (2 : ℝ) ^ (-(1 / 2 : ℝ)) ≤ 3 / 4 := by
      rw [Real.rpow_neg (by norm_num), inv_le_comm₀ (by positivity) (by norm_num)]
      rw [show (2 : ℝ) ^ (1 / 2 : ℝ) = Real.sqrt 2 by rw [Real.sqrt_eq_rpow]]
      rw [Real.le_sqrt (by norm_num) (by norm_num)]; norm_num
    calc (k : ℝ) ^ (-(1 / 2 : ℝ)) / ((k : ℝ) - 1) ≤ (k : ℝ) ^ (-(1 / 2 : ℝ)) / 1 :=
          div_le_div_of_nonneg_left (Real.rpow_nonneg hk0.le _) one_pos (by linarith)
      _ ≤ 3 / 4 := by rw [div_one]; linarith
  linarith

/-- AM–GM: `k^{−1/2} ≤ (kJ² + m²)/(2mJk)` for `m ≥ 1`. -/
lemma rpow_neg_half_le_amgm {k m : ℕ} (hk : 1 ≤ k) (hm : 1 ≤ m) :
    (k : ℝ) ^ (-(1 / 2 : ℝ)) ≤ ((k : ℝ) * J * J + (m : ℝ) * m) / (2 * m * J * k) := by
  have hk0 : (0 : ℝ) < k := by exact_mod_cast hk
  have hm0 : (0 : ℝ) < m := by exact_mod_cast hm
  have hJ : (0 : ℝ) < (J : ℝ) := by norm_num [J]
  set r := (k : ℝ) ^ (1 / 2 : ℝ) with hr
  have hr0 : 0 < r := Real.rpow_pos_of_pos hk0 _
  have hrr : r * r = k := by rw [hr, ← Real.rpow_add hk0]; norm_num
  have hinv : (k : ℝ) ^ (-(1 / 2 : ℝ)) = r / k := by
    rw [Real.rpow_neg hk0.le, ← hr, eq_div_iff hk0.ne', ← hrr]; field_simp
  rw [hinv, div_le_div_iff₀ hk0 (by positivity)]
  have hsq : 0 ≤ ((m : ℝ) - J * r) ^ 2 := sq_nonneg _
  have e : ((m : ℝ) - J * r) ^ 2 = (m : ℝ) * m - 2 * m * J * r + J * J * (r * r) := by ring
  rw [e, hrr] at hsq
  have h1 : 2 * (m : ℝ) * J * r ≤ k * J * J + m * m := by linarith
  nlinarith [mul_le_mul_of_nonneg_right h1 hk0.le]

/-- The rational factor dominates `bfac k`. -/
lemma bfac_le_bnum_div {k m : ℕ} (hk : 2 ≤ k) (hm : 1 ≤ m) :
    bfac k ≤ (bnum k m : ℝ) / (bden k m : ℝ) := by
  have h2 : (2 : ℝ) ≤ k := by exact_mod_cast hk
  have hk0 : (0 : ℝ) < k := by linarith
  have hk1 : (0 : ℝ) < (k : ℝ) - 1 := by linarith
  have hm0 : (0 : ℝ) < m := by exact_mod_cast hm
  have hJ : (0 : ℝ) < (J : ℝ) := by norm_num [J]
  have hcast1 : ((k - 1 : ℕ) : ℝ) = (k : ℝ) - 1 := by push_cast [show 1 ≤ k by omega]; ring
  have hden : (bden k m : ℝ) = 2 * m * J * k * k * ((k : ℝ) - 1) := by
    unfold bden; push_cast [show 1 ≤ k by omega]; ring
  have hnum : (bnum k m : ℝ) = 2 * m * J * k * k * ((k : ℝ) - 1) +
      ((k : ℝ) * J * J + (m : ℝ) * m) * k + 2 * m * J := by
    unfold bnum; push_cast [show 1 ≤ k by omega]; ring
  rw [hnum, hden]
  have h := rpow_neg_half_le_amgm (show 1 ≤ k by omega) hm
  have hpos : 0 < 2 * (m : ℝ) * J * k * k * ((k : ℝ) - 1) := by positivity
  have e : (2 * (m : ℝ) * J * k * k * ((k : ℝ) - 1) + ((k : ℝ) * J * J + (m : ℝ) * m) * k +
      2 * m * J) / (2 * (m : ℝ) * J * k * k * ((k : ℝ) - 1)) =
      1 + (((k : ℝ) * J * J + (m : ℝ) * m) / (2 * m * J * k)) / ((k : ℝ) - 1) +
        (k : ℝ)⁻¹ / ((k : ℝ) * ((k : ℝ) - 1)) := by
    field_simp
  rw [e]
  unfold bfac
  have := div_le_div_of_nonneg_right h hk1.le
  linarith

/-- `L · bnum/bden ≤ ⌈L · bnum/bden⌉`. -/
lemma le_ceil_div (a b : ℕ) (hb : 0 < b) : (a : ℝ) / b ≤ ((a + b - 1) / b : ℕ) := by
  have h : a ≤ b * ((a + b - 1) / b) := by
    have := Nat.div_add_mod (a + b - 1) b
    have := Nat.mod_lt (a + b - 1) hb
    omega
  rw [div_le_iff₀ (by exact_mod_cast hb)]
  exact_mod_cast (by linarith [h] : a ≤ ((a + b - 1) / b) * b)

lemma step_ge {k : ℕ} (hk : 2 ≤ k) (m L : ℕ) :
    (L : ℝ) * (if k.Prime then bfac k else 1) ≤ step k m L := by
  have h1 := one_le_bfac' hk
  have hL : (0 : ℝ) ≤ L := Nat.cast_nonneg L
  have hfac1 : (if k.Prime then bfac k else 1) ≤ bfac k := by split_ifs <;> linarith
  by_cases hw : witness k = true
  · rw [if_neg (witness_sound hw), mul_one]
    unfold step; rw [if_pos hw]
  · unfold step; rw [if_neg hw]
    by_cases hm : m = 0
    · rw [if_pos hm]; push_cast
      have := bfac_le_two hk
      nlinarith
    · rw [if_neg hm]
      have hm1 : 1 ≤ m := Nat.one_le_iff_ne_zero.mpr hm
      have hden : 0 < bden k m := by
        unfold bden
        exact Nat.mul_pos (Nat.mul_pos (Nat.mul_pos (Nat.mul_pos (Nat.mul_pos (by norm_num)
          (by omega)) (by norm_num [J])) (by omega)) (by omega)) (by omega)
      have hb := bfac_le_bnum_div hk hm1
      have hc := le_ceil_div (L * bnum k m) (bden k m) hden
      push_cast at hc
      calc (L : ℝ) * (if k.Prime then bfac k else 1) ≤ L * bfac k :=
            mul_le_mul_of_nonneg_left hfac1 hL
        _ ≤ L * ((bnum k m : ℝ) / bden k m) := mul_le_mul_of_nonneg_left hb hL
        _ = (L : ℝ) * bnum k m / bden k m := by ring
        _ ≤ _ := hc

/-- The head product over `[k, k+n)`. -/
def bhead (k n : ℕ) : ℝ := ∏ p ∈ (Finset.Ico k (k + n)).filter Nat.Prime, bfac p

lemma bhead_succ (k n : ℕ) : bhead k (n + 1) = (if k.Prime then bfac k else 1) * bhead (k + 1) n := by
  unfold bhead
  have : Finset.Ico k (k + (n + 1)) = insert k (Finset.Ico (k + 1) (k + 1 + n)) := by
    ext x; simp only [Finset.mem_Ico, Finset.mem_insert]; omega
  rw [this, Finset.filter_insert]
  split_ifs with hk
  · rw [Finset.prod_insert (by simp)]
  · rw [one_mul]

lemma bhead_nonneg (k n : ℕ) : 0 ≤ bhead k n :=
  Finset.prod_nonneg fun _ hp => le_trans zero_le_one (one_le_bfac (Finset.mem_filter.mp hp).2)

theorem loopP_ge (n : ℕ) : ∀ (k : ℕ) (s : ℕ × ℕ), 2 ≤ k →
    (s.2 : ℝ) * bhead k n ≤ (loopP n k s).2 := by
  induction n with
  | zero => intro k s _; simp [bhead, loopP]
  | succ n ih =>
    intro k s hk
    rw [bhead_succ]
    have h1 := step_ge hk (newton3 k s.1) s.2
    have h2 := ih (k + 1) (stepP k s) (by omega)
    show (s.2 : ℝ) * ((if k.Prime then bfac k else 1) * bhead (k + 1) n) ≤ (loopP n (k + 1) (stepP k s)).2
    calc (s.2 : ℝ) * ((if k.Prime then bfac k else 1) * bhead (k + 1) n)
        = ((s.2 : ℝ) * (if k.Prime then bfac k else 1)) * bhead (k + 1) n := by ring
      _ ≤ ((stepP k s).2 : ℝ) * bhead (k + 1) n :=
          mul_le_mul_of_nonneg_right h1 (bhead_nonneg _ _)
      _ ≤ _ := h2

lemma loopP_add (a b k : ℕ) (s : ℕ × ℕ) : loopP (a + b) k s = loopP b (k + a) (loopP a k s) := by
  induction a generalizing k s with
  | zero => simp [loopP]
  | succ a ih =>
    rw [show a + 1 + b = (a + b) + 1 by ring]
    show loopP (a + b) (k + 1) (stepP k s) = loopP b (k + (a + 1)) (loopP a (k + 1) (stepP k s))
    rw [ih, show k + 1 + a = k + (a + 1) by ring]

lemma loopP_chain {a b k k' : ℕ} {s s' : ℕ × ℕ} (hk : k + a = k') (h : loopP a k s = s') :
    loopP (a + b) k s = loopP b k' s' := by
  rw [loopP_add, hk, h]

/-- The whole run, from the chunk theorems. -/
theorem loopP_full : loopP 99999 2 (10000, 100000000000000000000) = (bM, bL) := by
  rw [show (99999 : ℕ) = 20000 + (20000 + (20000 + (20000 + 19999))) by norm_num,
    loopP_chain (k' := 20002) (by norm_num) chunk0, loopP_chain (k' := 40002) (by norm_num) chunk1,
    loopP_chain (k' := 60002) (by norm_num) chunk2, loopP_chain (k' := 80002) (by norm_num) chunk3,
    chunk4]
  rfl

/-- **Head:** `∏_{p ≤ 10⁵} bfac(p) ≤ bL/10^20`. -/
theorem head_le : bhead 2 99999 ≤ (bL : ℝ) / 100000000000000000000 := by
  have h := loopP_ge 99999 2 (10000, 100000000000000000000) le_rfl
  rw [loopP_full] at h
  push_cast at h
  rw [le_div_iff₀ (by norm_num)]
  linarith

/-! ### The tail: Abel summation against Chebyshev's `θ` -/

/-- `g(n) = n^{−3/2}/log n`. -/
def gTail (n : ℕ) : ℝ := (n : ℝ) ^ (-(3 / 2 : ℝ)) / Real.log n

/-- `A(n) = θ(n) = ∑_{p ≤ n} log p`. -/
def Ath (n : ℕ) : ℝ := ∑ p ∈ (Finset.Icc 1 n).filter Nat.Prime, Real.log p

lemma Ath_nonneg (n : ℕ) : 0 ≤ Ath n :=
  Finset.sum_nonneg fun p _ => Real.log_natCast_nonneg p

lemma Ath_succ (n : ℕ) :
    Ath (n + 1) = Ath n + (if (n + 1).Prime then Real.log (n + 1 : ℕ) else 0) := by
  unfold Ath
  rw [Finset.sum_filter, Finset.sum_filter, Finset.sum_Icc_succ_top (by omega)]

lemma Ath_le (n : ℕ) : Ath n ≤ Real.log 4 * n := by
  have h := Chebyshev.theta_le_log4_mul_x (Nat.cast_nonneg n : (0 : ℝ) ≤ n)
  refine le_trans (le_of_eq ?_) h
  unfold Ath Chebyshev.theta
  rw [Nat.floor_natCast]
  congr 1

lemma gT_pos {n : ℕ} (hn : 2 ≤ n) : 0 < gTail n := by
  have h2 : (2 : ℝ) ≤ n := by exact_mod_cast hn
  unfold gTail
  exact div_pos (Real.rpow_pos_of_pos (by linarith) _) (Real.log_pos (by linarith))

lemma gT_anti {n : ℕ} (hn : 2 ≤ n) : gTail (n + 1) ≤ gTail n := by
  have h2 : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hn0 : (0 : ℝ) < n := by linarith
  unfold gTail
  push_cast
  apply div_le_div₀ (Real.rpow_nonneg hn0.le _)
    (Real.rpow_le_rpow_of_nonpos hn0 (by linarith) (by norm_num))
    (Real.log_pos (by linarith)) (Real.log_le_log hn0 (by linarith))

/-- The Abel-summation invariant (as in `tail_invariant`). For `N ≥ P+1 ≥ 3`:
`∑_{P<n≤N} [n prime] n^{−3/2} + (cN − A(N)) g(N) ≤ c (P+1) g(P+1) + c ∑_{P+1<n≤N} g(n)`, `c = log 4`. -/
lemma abel_invariant (P : ℕ) (hP : 2 ≤ P) (N : ℕ) (hN : P + 1 ≤ N) :
    ∑ n ∈ Finset.Ioc P N, (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0) +
        (Real.log 4 * N - Ath N) * gTail N ≤
      Real.log 4 * (P + 1 : ℕ) * gTail (P + 1) +
        Real.log 4 * ∑ n ∈ Finset.Ioc (P + 1) N, gTail n := by
  have hc : 0 < Real.log 4 := Real.log_pos (by norm_num)
  -- `[n prime] n^{−3/2} = [n prime] log n · g(n)`
  have hag : ∀ n : ℕ, 2 ≤ n → (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0) =
      (if n.Prime then Real.log n else 0) * gTail n := by
    intro n hn
    have h2 : (2 : ℝ) ≤ n := by exact_mod_cast hn
    have hl : Real.log n ≠ 0 := (Real.log_pos (by linarith)).ne'
    split_ifs
    · unfold gTail; field_simp
    · simp
  induction N, hN using Nat.le_induction with
  | base =>
    rw [show Finset.Ioc P (P + 1) = {P + 1} by ext x; simp only [Finset.mem_Ioc, Finset.mem_singleton]; omega, Finset.sum_singleton,
      show Finset.Ioc (P + 1) (P + 1) = ∅ by simp, Finset.sum_empty, mul_zero, add_zero,
      hag (P + 1) (by omega), Ath_succ]
    have := Ath_nonneg P
    have := gT_pos (show 2 ≤ P + 1 by omega)
    push_cast
    nlinarith
  | succ N hN ih =>
    rw [Finset.sum_Ioc_succ_top (by omega), Finset.sum_Ioc_succ_top (by omega),
      hag (N + 1) (by omega)]
    have hA := Ath_le N
    have hg := gT_anti (show 2 ≤ N by omega)
    have hg0 := gT_pos (show 2 ≤ N + 1 by omega)
    rw [Ath_succ]
    push_cast at ih ⊢
    have hmono : (Real.log 4 * N - Ath N) * gTail (N + 1) ≤ (Real.log 4 * N - Ath N) * gTail N :=
      mul_le_mul_of_nonneg_left hg (by linarith)
    nlinarith

/-- `n^{−3/2} ≤ 2((n−1)^{−1/2} − n^{−1/2})` for `n ≥ 2`, and the telescoped tail. -/
lemma sum_Ioc_rpow_le (a N : ℕ) (ha : 1 ≤ a) :
    ∑ n ∈ Finset.Ioc a N, (n : ℝ) ^ (-(3 / 2 : ℝ)) ≤ 2 * (a : ℝ) ^ (-(1 / 2 : ℝ)) := by
  -- termwise: `n^{-3/2} ≤ 2 ((n-1)^{-1/2} - n^{-1/2})`
  have key : ∀ n : ℕ, 2 ≤ n →
      (n : ℝ) ^ (-(3 / 2 : ℝ)) ≤ 2 * (((n - 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) - (n : ℝ) ^ (-(1 / 2 : ℝ))) := by
    intro n hn
    have h2 : (2 : ℝ) ≤ n := by exact_mod_cast hn
    have hn0 : (0 : ℝ) < n := by linarith
    have hn1 : ((n - 1 : ℕ) : ℝ) = (n : ℝ) - 1 := by push_cast [show 1 ≤ n by omega]; ring
    rw [hn1]
    set u := (n : ℝ) ^ (1 / 2 : ℝ) with hu
    set v := ((n : ℝ) - 1) ^ (1 / 2 : ℝ) with hv
    have hu0 : 0 < u := Real.rpow_pos_of_pos hn0 _
    have hv0 : 0 < v := Real.rpow_pos_of_pos (by linarith) _
    have huu : u * u = n := by rw [hu, ← Real.rpow_add hn0]; norm_num
    have hvv : v * v = (n : ℝ) - 1 := by rw [hv, ← Real.rpow_add (by linarith)]; norm_num
    have hvu : v ≤ u := Real.rpow_le_rpow (by linarith) (by linarith) (by norm_num)
    have e1 : (n : ℝ) ^ (-(3 / 2 : ℝ)) = 1 / (u * u * u) := by
      rw [show -(3 / 2 : ℝ) = -(1 / 2) + (-1) by norm_num, Real.rpow_add hn0, Real.rpow_neg_one,
        Real.rpow_neg hn0.le, ← hu, ← huu]; field_simp
    have e2 : (n : ℝ) ^ (-(1 / 2 : ℝ)) = 1 / u := by rw [Real.rpow_neg hn0.le, ← hu, one_div]
    have e3 : ((n : ℝ) - 1) ^ (-(1 / 2 : ℝ)) = 1 / v := by
      rw [Real.rpow_neg (by linarith), ← hv, one_div]
    rw [e1, e2, e3]
    -- `1/u³ ≤ 2(1/v − 1/u) = 2(u−v)/(uv)`, and `u − v = 1/(u+v) ≥ 1/(2u)`
    have huv : (u - v) * (u + v) = 1 := by nlinarith
    rw [div_le_iff₀ (by positivity)]
    have : 2 * (1 / v - 1 / u) * (u * u * u) = 2 * (u - v) * u * u / v := by field_simp
    rw [this, le_div_iff₀ hv0]
    nlinarith [mul_pos hu0 hv0, mul_pos (mul_pos hu0 hu0) hv0]
  -- telescoping
  have tele : ∀ M : ℕ, ∑ n ∈ Finset.Ioc a (a + M), (n : ℝ) ^ (-(3 / 2 : ℝ)) ≤
      2 * ((a : ℝ) ^ (-(1 / 2 : ℝ)) - ((a + M : ℕ) : ℝ) ^ (-(1 / 2 : ℝ))) := by
    intro M
    induction M with
    | zero => simp
    | succ M ih =>
      rw [show a + (M + 1) = a + M + 1 by ring, Finset.sum_Ioc_succ_top (by omega)]
      have := key (a + M + 1) (by omega)
      rw [show a + M + 1 - 1 = a + M by omega] at this
      linarith
  rcases le_or_gt N a with h | h
  · rw [Finset.Ioc_eq_empty (by omega), Finset.sum_empty]
    have : 0 ≤ (a : ℝ) ^ (-(1 / 2 : ℝ)) := Real.rpow_nonneg (Nat.cast_nonneg _) _
    linarith
  · have := tele (N - a)
    rw [show a + (N - a) = N by omega] at this
    have : 0 ≤ ((N : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) := Real.rpow_nonneg (Nat.cast_nonneg _) _
    linarith

/-- **Chebyshev tail:** `∑_{P < p ≤ N, p prime} p^{−3/2} ≤ 3 log 4 (P+1)^{−1/2}/log(P+1)`. -/
theorem sum_prime_rpow_tail_le (P : ℕ) (hP : 2 ≤ P) (N : ℕ) :
    ∑ n ∈ Finset.Ioc P N, (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0) ≤
      3 * Real.log 4 * ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) / Real.log (P + 1 : ℕ) := by
  have hc : 0 < Real.log 4 := Real.log_pos (by norm_num)
  have hP1 : (3 : ℝ) ≤ ((P + 1 : ℕ) : ℝ) := by push_cast; exact_mod_cast (by omega : 3 ≤ P + 1)
  have hlog : 0 < Real.log (P + 1 : ℕ) := Real.log_pos (by linarith)
  rcases le_or_gt N P with h | h
  · rw [Finset.Ioc_eq_empty (by omega), Finset.sum_empty]; positivity
  have hinv := abel_invariant P hP N h
  have hAN : 0 ≤ (Real.log 4 * N - Ath N) * gTail N :=
    mul_nonneg (by linarith [Ath_le N]) (gT_pos (by omega)).le
  -- `∑_{P+1<n≤N} g(n) ≤ (1/log(P+1)) ∑ n^{−3/2} ≤ 2(P+1)^{−1/2}/log(P+1)`
  have hgs : ∑ n ∈ Finset.Ioc (P + 1) N, gTail n ≤
      (1 / Real.log (P + 1 : ℕ)) * (2 * ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ))) := by
    refine le_trans ?_ (mul_le_mul_of_nonneg_left (sum_Ioc_rpow_le (P + 1) N (by omega))
      (by positivity))
    rw [Finset.mul_sum]
    refine Finset.sum_le_sum fun n hn => ?_
    have hn : P + 1 < n := (Finset.mem_Ioc.mp hn).1
    have hn0 : (0 : ℝ) < n := by exact_mod_cast (show 0 < n by omega)
    unfold gTail
    rw [div_eq_mul_inv, one_div, mul_comm]
    refine mul_le_mul_of_nonneg_right ?_ (Real.rpow_nonneg hn0.le _)
    exact inv_anti₀ hlog (Real.log_le_log (by linarith) (by exact_mod_cast hn.le))
  have hgP : ((P + 1 : ℕ) : ℝ) * gTail (P + 1) = ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) /
      Real.log (P + 1 : ℕ) := by
    unfold gTail
    have hp0 : (0 : ℝ) < ((P + 1 : ℕ) : ℝ) := by linarith
    rw [show -(3 / 2 : ℝ) = -(1 / 2) + (-1) by norm_num, Real.rpow_add hp0, Real.rpow_neg_one]
    field_simp
  have hc' : 0 ≤ Real.log 4 := hc.le
  have hS : ∑ n ∈ Finset.Ioc P N, (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0) ≤
      Real.log 4 * (((P + 1 : ℕ) : ℝ) * gTail (P + 1)) +
        Real.log 4 * ∑ n ∈ Finset.Ioc (P + 1) N, gTail n := by
    have : Real.log 4 * ((P + 1 : ℕ) : ℝ) * gTail (P + 1) =
        Real.log 4 * (((P + 1 : ℕ) : ℝ) * gTail (P + 1)) := by ring
    linarith
  rw [hgP] at hS
  have := mul_le_mul_of_nonneg_left hgs hc'
  calc ∑ n ∈ Finset.Ioc P N, (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0)
      ≤ Real.log 4 * (((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) / Real.log (P + 1 : ℕ)) +
        Real.log 4 * ((1 / Real.log (P + 1 : ℕ)) * (2 * ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)))) := by
        linarith
    _ = 3 * Real.log 4 * ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) / Real.log (P + 1 : ℕ) := by
        field_simp; ring

/-! ### Assembly: `B < 3.73` -/

/-- `bfac p − 1 ≤ (1 + 3/P) p^{−3/2}` for `p > P ≥ 4`. -/
lemma bfac_sub_one_le_tail {P p : ℕ} (hP : 4 ≤ P) (hp : P < p) :
    bfac p - 1 ≤ (1 + 3 / (P : ℝ)) * (p : ℝ) ^ (-(3 / 2 : ℝ)) := by
  have hP4 : (4 : ℝ) ≤ P := by exact_mod_cast hP
  have hpP : (P : ℝ) + 1 ≤ p := by exact_mod_cast hp
  have hp0 : (0 : ℝ) < p := by linarith
  set u := (p : ℝ) ^ (1 / 2 : ℝ) with hu
  have hu0 : 0 < u := Real.rpow_pos_of_pos hp0 _
  have huu : u * u = p := by rw [hu, ← Real.rpow_add hp0]; norm_num
  have hu2 : 2 < u := by nlinarith
  have e1 : (p : ℝ) ^ (-(1 / 2 : ℝ)) = 1 / u := by rw [Real.rpow_neg hp0.le, ← hu, one_div]
  have e3 : (p : ℝ) ^ (-(3 / 2 : ℝ)) = 1 / (u * u * u) := by
    rw [show -(3 / 2 : ℝ) = -(1 / 2) + (-1) by norm_num, Real.rpow_add hp0, Real.rpow_neg_one, e1,
      ← huu]; field_simp
  unfold bfac
  rw [e1, e3, ← huu]
  have hP0 : (0 : ℝ) < P := by linarith
  have hu21 : 0 < u * u - 1 := by nlinarith
  -- `A = 1/(u(u²−1)) ≤ (1 + 2/P)/u³` and `B = 1/(u⁴(u²−1)) ≤ (1/P)/u³`
  have tA : 1 / u / (u * u - 1) ≤ (1 + 2 / (P : ℝ)) * (1 / (u * u * u)) := by
    rw [div_div, div_le_iff₀ (by positivity)]
    have : (1 + 2 / (P : ℝ)) * (1 / (u * u * u)) * (u * (u * u - 1)) =
        (1 + 2 / (P : ℝ)) * (u * u - 1) / (u * u) := by field_simp
    rw [this, le_div_iff₀ (by positivity)]
    have : 2 / (P : ℝ) * (u * u) ≥ 1 + 2 / (P : ℝ) := by
      rw [ge_iff_le, ← sub_nonneg]
      have : 2 / (P : ℝ) * (u * u) - (1 + 2 / (P : ℝ)) = (2 * (u * u) - P - 2) / P := by
        field_simp; ring
      rw [this]; apply div_nonneg _ hP0.le; nlinarith
    nlinarith
  have tB : (u * u)⁻¹ / (u * u * (u * u - 1)) ≤ 1 / (P : ℝ) * (1 / (u * u * u)) := by
    have e1 : (u * u)⁻¹ / (u * u * (u * u - 1)) = 1 / (u * u * (u * u * (u * u - 1))) := by
      rw [inv_eq_one_div, div_div]
    have e2 : 1 / (P : ℝ) * (1 / (u * u * u)) = 1 / (P * (u * u * u)) := by
      rw [one_div_mul_one_div]
    rw [e1, e2]
    apply one_div_le_one_div_of_le (by positivity)
    have hPu : (P : ℝ) ≤ u * u - 1 := by linarith
    have h3 : 0 < u * u * u := by positivity
    have h4 : u * u - 1 ≤ u * (u * u - 1) := by nlinarith
    calc (P : ℝ) * (u * u * u) ≤ (u * (u * u - 1)) * (u * u * u) :=
          mul_le_mul_of_nonneg_right (hPu.trans h4) h3.le
      _ = u * u * (u * u * (u * u - 1)) := by ring
  have : (1 + 3 / (P : ℝ)) * (1 / (u * u * u)) =
      (1 + 2 / (P : ℝ)) * (1 / (u * u * u)) + 1 / (P : ℝ) * (1 / (u * u * u)) := by ring
  linarith

/-- The tail sum: for a finite set `U` of primes `> P` (`P ≥ 4`), `∑_{p∈U} (bfac p − 1) ≤ T(P)`. -/
lemma tail_sum_le (P : ℕ) (hP : 4 ≤ P) (U : Finset ℕ) (hU : ∀ p ∈ U, p.Prime ∧ P < p) :
    ∑ p ∈ U, (bfac p - 1) ≤ (1 + 3 / (P : ℝ)) *
      (3 * Real.log 4 * ((P + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) / Real.log (P + 1 : ℕ)) := by
  set N := U.sup id with hN
  have hsub : U ⊆ (Finset.Ioc P N).filter Nat.Prime := by
    intro p hp
    rw [Finset.mem_filter, Finset.mem_Ioc]
    exact ⟨⟨(hU p hp).2, Finset.le_sup (f := id) hp⟩, (hU p hp).1⟩
  have hc : 0 ≤ 1 + 3 / (P : ℝ) := by positivity
  calc ∑ p ∈ U, (bfac p - 1) ≤ ∑ p ∈ U, (1 + 3 / (P : ℝ)) * (p : ℝ) ^ (-(3 / 2 : ℝ)) :=
        Finset.sum_le_sum fun p hp => bfac_sub_one_le_tail hP (hU p hp).2
    _ ≤ ∑ p ∈ (Finset.Ioc P N).filter Nat.Prime, (1 + 3 / (P : ℝ)) * (p : ℝ) ^ (-(3 / 2 : ℝ)) :=
        Finset.sum_le_sum_of_subset_of_nonneg hsub fun p _ _ =>
          mul_nonneg hc (Real.rpow_nonneg (Nat.cast_nonneg _) _)
    _ = (1 + 3 / (P : ℝ)) * ∑ n ∈ Finset.Ioc P N,
          (if n.Prime then (n : ℝ) ^ (-(3 / 2 : ℝ)) else 0) := by
        rw [Finset.sum_filter, Finset.mul_sum]
        exact Finset.sum_congr rfl fun n _ => by split_ifs <;> simp
    _ ≤ _ := mul_le_mul_of_nonneg_left (sum_prime_rpow_tail_le P (by omega) N) hc

/-- `exp x ≤ 1/(1 − x)` for `x < 1`. -/
lemma exp_le_inv_one_sub {x : ℝ} (hx : x < 1) : Real.exp x ≤ 1 / (1 - x) := by
  have h := Real.add_one_le_exp (-x)
  have hpos := Real.exp_pos x
  have he : Real.exp x * Real.exp (-x) = 1 := by rw [← Real.exp_add]; simp
  rw [le_div_iff₀ (by linarith)]
  nlinarith

/-- `Nat.Primes ↪ ℕ`. -/
def primesEmb : Nat.Primes ↪ ℕ := ⟨fun p => p, Nat.Primes.coe_nat_injective⟩

/-- The head set `{p ≤ 10⁵ prime}`. -/
def headP : Finset ℕ := (Finset.Ico 2 100001).filter Nat.Prime

lemma bhead_eq : bhead 2 99999 = ∏ p ∈ headP, bfac p := rfl

lemma bfac_pos {p : ℕ} (hp : 2 ≤ p) : 0 < bfac p := lt_of_lt_of_le one_pos (one_le_bfac' hp)

/-- The numerical tail constant: `T(10⁵) ≤ 0.0011868`. -/
lemma tail_const_le :
    (1 + 3 / ((100000 : ℕ) : ℝ)) * (3 * Real.log 4 * ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) /
      Real.log (100000 + 1 : ℕ)) ≤ 0.0011868 := by
  have hl2 := Real.log_two_lt_d9
  have hl2' := Real.log_two_gt_d9
  have hlog4 : Real.log 4 ≤ 1.3863 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.log_pow]; push_cast; linarith
  have hlog4' : 0 < Real.log 4 := Real.log_pos (by norm_num)
  have hlgN : 11.0903 ≤ Real.log (100000 + 1 : ℕ) := by
    have : Real.log (65536 : ℝ) ≤ Real.log ((100000 + 1 : ℕ) : ℝ) :=
      Real.log_le_log (by norm_num) (by norm_num)
    rw [show (65536 : ℝ) = 2 ^ 16 by norm_num, Real.log_pow] at this
    push_cast at this; linarith
  have hr : ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) ≤ 1 / 316 := by
    rw [Real.rpow_neg (by positivity), ← Real.sqrt_eq_rpow, one_div]
    apply inv_anti₀ (by norm_num)
    rw [Real.le_sqrt (by norm_num) (by positivity)]; norm_num
  have hr0 : 0 ≤ ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) := Real.rpow_nonneg (by positivity) _
  have hlg0 : 0 < Real.log (100000 + 1 : ℕ) := Real.log_pos (by norm_num)
  calc (1 + 3 / ((100000 : ℕ) : ℝ)) * (3 * Real.log 4 * ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) /
        Real.log (100000 + 1 : ℕ))
      ≤ (1 + 3 / ((100000 : ℕ) : ℝ)) * (3 * 1.3863 * (1 / 316) / 11.0903) := by
        apply mul_le_mul_of_nonneg_left _ (by positivity)
        rw [div_le_div_iff₀ hlg0 (by norm_num)]
        have h1 : 3 * Real.log 4 * ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) ≤ 3 * 1.3863 * (1 / 316) := by
          have := mul_le_mul hlog4 hr hr0 (by norm_num)
          nlinarith
        have h2 : 0 ≤ 3 * Real.log 4 * ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) := by positivity
        nlinarith
    _ ≤ 0.0011868 := by norm_num

/-- **`B < 3.73`** (`lem:fS`(iii), certified). -/
theorem Bconst_lt : Bconst < 3.73 := by
  set T : ℝ := (1 + 3 / ((100000 : ℕ) : ℝ)) * (3 * Real.log 4 *
    ((100000 + 1 : ℕ) : ℝ) ^ (-(1 / 2 : ℝ)) / Real.log (100000 + 1 : ℕ)) with hT
  have hT0 : T ≤ 0.0011868 := tail_const_le
  have hhead := head_le
  rw [bhead_eq] at hhead
  have hHpos : 0 < ∏ p ∈ headP, bfac p :=
    Finset.prod_pos fun p hp => bfac_pos (Finset.mem_Ico.mp (Finset.mem_filter.mp hp).1).1
  have hlogH : Real.log (∏ p ∈ headP, bfac p) = ∑ p ∈ headP, Real.log (bfac p) :=
    Real.log_prod fun p hp => (bfac_pos (Finset.mem_Ico.mp (Finset.mem_filter.mp hp).1).1).ne'
  -- every finite partial sum of `log bfac` over the primes is `≤ log H + T`
  have hsum : ∀ U : Finset Nat.Primes, ∑ p ∈ U, Real.log (bfac p) ≤
      Real.log (∏ p ∈ headP, bfac p) + T := by
    intro U
    rw [hlogH, ← Finset.sum_filter_add_sum_filter_not U (fun p : Nat.Primes => (p : ℕ) ≤ 100000)]
    have h1 : ∑ p ∈ U.filter (fun p : Nat.Primes => (p : ℕ) ≤ 100000), Real.log (bfac p) ≤
        ∑ p ∈ headP, Real.log (bfac p) := by
      rw [show ∑ p ∈ U.filter (fun p : Nat.Primes => (p : ℕ) ≤ 100000), Real.log (bfac p) =
          ∑ n ∈ (U.filter (fun p : Nat.Primes => (p : ℕ) ≤ 100000)).map primesEmb, Real.log (bfac n) by
        rw [Finset.sum_map]; rfl]
      refine Finset.sum_le_sum_of_subset_of_nonneg (fun n hn => ?_) fun n hn _ =>
        Real.log_nonneg (one_le_bfac' (Finset.mem_Ico.mp (Finset.mem_filter.mp hn).1).1)
      obtain ⟨p, hp, rfl⟩ := Finset.mem_map.mp hn
      obtain ⟨-, hp1⟩ := Finset.mem_filter.mp hp
      change (p : ℕ) ∈ headP
      simp only [headP, Finset.mem_filter, Finset.mem_Ico]
      exact ⟨⟨p.2.two_le, by omega⟩, p.2⟩
    have h2 : ∑ p ∈ U.filter (fun p : Nat.Primes => ¬ (p : ℕ) ≤ 100000), Real.log (bfac p) ≤ T := by
      calc ∑ p ∈ U.filter (fun p : Nat.Primes => ¬ (p : ℕ) ≤ 100000), Real.log (bfac p)
          ≤ ∑ p ∈ U.filter (fun p : Nat.Primes => ¬ (p : ℕ) ≤ 100000), (bfac p - 1) :=
            Finset.sum_le_sum fun p _ => Real.log_le_sub_one_of_pos (bfac_pos p.2.two_le)
        _ = ∑ n ∈ (U.filter (fun p : Nat.Primes => ¬ (p : ℕ) ≤ 100000)).map primesEmb, (bfac n - 1) := by
            rw [Finset.sum_map]; rfl
        _ ≤ T := by
            refine tail_sum_le 100000 (by norm_num) _ fun n hn => ?_
            obtain ⟨p, hp, rfl⟩ := Finset.mem_map.mp hn
            obtain ⟨-, hp1⟩ := Finset.mem_filter.mp hp
            exact ⟨p.2, by show 100000 < (p : ℕ); omega⟩
    linarith
  have hlogpos : ∀ p : Nat.Primes, 0 ≤ Real.log (bfac p) := fun p =>
    Real.log_nonneg (one_le_bfac p.2)
  have htsum : ∑' p : Nat.Primes, Real.log (bfac p) ≤ Real.log (∏ p ∈ headP, bfac p) + T :=
    Real.tsum_le_of_sum_le hlogpos hsum
  have hB : Bconst = Real.exp (∑' p : Nat.Primes, Real.log (bfac p)) :=
    (Real.rexp_tsum_eq_tprod (fun p => bfac_pos p.2.two_le) summable_log_bfac).symm
  have hT1 : T < 1 := by linarith
  calc Bconst ≤ Real.exp (Real.log (∏ p ∈ headP, bfac p) + T) := by
        rw [hB]; exact Real.exp_le_exp.mpr htsum
    _ = (∏ p ∈ headP, bfac p) * Real.exp T := by rw [Real.exp_add, Real.exp_log hHpos]
    _ ≤ ((bL : ℝ) / 100000000000000000000) * (1 / (1 - 0.0011868)) := by
        apply mul_le_mul hhead _ (Real.exp_pos T).le (by positivity)
        refine (exp_le_inv_one_sub hT1).trans ?_
        apply one_div_le_one_div_of_le (by norm_num); linarith
    _ < 3.73 := by norm_num [bL]

/-- **`lem:fS`** (all four parts), sorry-free. -/
theorem lemfS_proof : lemfS_Statement := lemfS_of_Bconst Bconst_lt

end Families.Phase1.B
