# Generator for Families/Phase1/B/BconstData.lean, chunked version.
# Simulates the Lean loop exactly (Nat semantics) and emits one `decide +kernel` theorem per chunk.
import sys
P=int(sys.argv[1]); out_path=sys.argv[2]; CH=int(sys.argv[3]) if len(sys.argv)>3 else 20000
def primes_upto(n):
    s=bytearray([1])*(n+1); s[0]=s[1]=0
    for i in range(2,int(n**0.5)+1):
        if s[i]: s[i*i::i]=bytearray(len(s[i*i::i]))
    return [i for i in range(n+1) if s[i]]
r=int(P**0.5)
while (r+1)*(r+1)<=P: r+=1
small=primes_upto(r)
J=10000
def witness(k): return any(2<=d and d<k and k%d==0 for d in small)
def newton(k,m): return (m + (k*J*J)//m)//2 if m>0 else 0
def newton3(k,m): return newton(k,newton(k,newton(k,m)))
def bnum(k,m): return 2*m*J*k*k*(k-1)+(k*J*J+m*m)*k+2*m*J
def bden(k,m): return 2*m*J*k*k*(k-1)
def step(k,m,L):
    if witness(k): return L
    if m==0: return 2*L
    return (L*bnum(k,m)+bden(k,m)-1)//bden(k,m)
S=10**20
state=(J,S); k=2; total=P-1
chunks=[]
done=0
while done<total:
    n=min(CH,total-done)
    k0=k; s0=state
    m,L=state
    for _ in range(n):
        m=newton3(k,m); L=step(k,m,L); k+=1
    state=(m,L); done+=n
    chunks.append((n,k0,s0,state))
print(f"final k={k} L={state[1]} L/S={state[1]/S}",file=sys.stderr)
thms=[]
for i,(n,k0,s0,s1) in enumerate(chunks):
    thms.append(f"theorem chunk{i} : loopP {n} {k0} ({s0[0]}, {s0[1]}) = ({s1[0]}, {s1[1]}) := by\n  decide +kernel\n")
chunk_list=", ".join(f"({n}, {k0})" for (n,k0,_,_) in chunks)
out=f'''/-
Kernel-checked data for the upper bound `B < 3.73` (`Families.Phase1.B.BconstCert`).

`loopP (P-1) 2 (J, S)` runs over `k = 2, …, P = {P}` with state `(m, L)`: `m ← newton3 k m`
(three Newton steps for `√(kJ²)`), and `L` (initially `S = 10^20`) is multiplied by the rational upper bound
`bnum/bden = 1 + (kJ² + m²)/(2mJk(k−1)) + 1/(k²(k−1)) ≥ 1 + k^{{-1/2}}/(k−1) + 1/(k²(k−1))`
(AM–GM: `k^{{-1/2}} ≤ (kJ² + m²)/(2mJk)` for every `m ≥ 1`; soundness does not depend on `m`), rounded
**up**, unless trial division by an entry `d` of `smallDivs` with `2 ≤ d < k` exhibits `k` as composite.
Keeping an uncertified composite only enlarges the product (all factors are `≥ 1`). The run is split into
{len(chunks)} chunks (`chunk0`, …) with explicit intermediate states, each checked by `decide +kernel`
(no `native_decide`). Generated by `gen_bconst2.py` (in this directory). Imports nothing.
-/

namespace Families.BconstData

/-- Trial divisors (the primes `≤ {r}`; `{r+1}² > {P}`). -/
def smallDivs : List Nat := {small}

/-- `true` only if some `d ∈ smallDivs` with `2 ≤ d < k` divides `k` (so `k` is composite). -/
def witness (k : Nat) : Bool :=
  smallDivs.any (fun d => decide (2 ≤ d) && decide (d < k) && k % d == 0)

/-- The scale of the square-root approximation. -/
def J : Nat := {J}

/-- One Newton step for `√(k J²)`. -/
def newton (k m : Nat) : Nat := (m + k * J * J / m) / 2

def newton3 (k m : Nat) : Nat := newton k (newton k (newton k m))

def bnum (k m : Nat) : Nat := 2 * m * J * k * k * (k - 1) + (k * J * J + m * m) * k + 2 * m * J

def bden (k m : Nat) : Nat := 2 * m * J * k * k * (k - 1)

/-- One step on `L`: `L ↦ ⌈L · bnum/bden⌉` unless `k` is certified composite (`2L` if `m = 0`). -/
def step (k m L : Nat) : Nat :=
  if witness k = true then L else if m = 0 then 2 * L else (L * bnum k m + bden k m - 1) / bden k m

/-- One step on the state `(m, L)`. -/
def stepP (k : Nat) (s : Nat × Nat) : Nat × Nat := (newton3 k s.1, step k (newton3 k s.1) s.2)

/-- Run `stepP` for `k, k+1, …, k+n-1`. -/
def loopP : Nat → Nat → Nat × Nat → Nat × Nat
  | 0, _, s => s
  | n + 1, k, s => loopP n (k + 1) (stepP k s)

/-- The final integer: `∏_{{p ≤ {P}}} bfac p ≤ bL/S`, `S = 10^20`. -/
def bL : Nat := {state[1]}

/-- The final `m`. -/
def bM : Nat := {state[0]}

{chr(10).join(thms)}
end Families.BconstData
'''
open(out_path,'w').write(out)
print(chunk_list,file=sys.stderr)
