"""Generate FamiliesH/V/CertData.lean: the n = 400 certificate step heights for `certH`
(Theorem 1.4(a), Lean package V, Proposition 9.24 of the paper, column (a) of the kappa-table, C = 1).

Heights: exactly the procedure of the paper's ancillary script certify_hybrid.py
(float KKT solve, symmetrise, round at scale 1e9, symmetrise), imported from there (no copy). It is looked up in
  ../..                 (the paper's anc/ directory, when this project is shipped as anc/lean/),
  ../../paper/anc       (the paper's anc/ directory, when this project sits next to the paper sources)
relative to this script; the first that contains certify_hybrid.py is used.

Before emitting the Lean file, every inequality is checked in exact integer arithmetic, together with the
consistency of the denominator-cleared formula with the exact rational value of Q:
  1e6 * (6 p D^2 cd X + Y) <= 6 B p^2 D cd S^2,
X = sum m_i^2, Y = sum_{i,j} m_i m_j ksB(i-j), S = sum m_i, beta = p/q, D = 400 q, h = p/D,
ksB(k) = GsB(k+1) - 2 GsB(k) + GsB(k-1), GsB(k) = 6 D^3 cd G(|k| p / D)   (as in FamiliesH/V/CertDefs.lean).

Run from anywhere (single core suffices; about a minute):
  OMP_NUM_THREADS=1 taskset -c 0 python3 scripts/gen_hybrid_data.py [--out PATH]
Default output: ../FamiliesH/V/CertData.lean relative to this script. Requires numpy and scipy (the
certify_hybrid.py dependencies).
"""
import os
import sys
from fractions import Fraction as Fr

HERE = os.path.dirname(os.path.abspath(__file__))
CANDIDATES = [os.path.join(HERE, '..', '..'), os.path.join(HERE, '..', '..', 'paper', 'anc')]
_found = [d for d in CANDIDATES if os.path.isfile(os.path.join(d, 'certify_hybrid.py'))]
if not _found:
    sys.exit("certify_hybrid.py not found; looked in: " + ", ".join(os.path.normpath(d) for d in CANDIDATES))
sys.path.insert(0, _found[0])
from certify_hybrid import solve_float, exact_Q  # noqa: E402

N = 400
ROWS = [("K1", "1", 3, 2, "0.865673"), ("K2", "2", 4, 3, "0.824355"), ("K3", "3", 5, 4, "0.797213"),
        ("K5", "5", 7, 6, "0.764149"), ("K10", "10", 12, 11, "0.727484")]


def Gs(cn, cd, p, D, k):
    m = abs(k) * p
    if m <= D:
        return cd * m ** 3
    return cd * D ** 3 + 3 * cd * D ** 2 * (m - D) + 3 * cn * D * (m - D) ** 2


def ks(cn, cd, p, D, k):
    return Gs(cn, cd, p, D, k + 1) - 2 * Gs(cn, cd, p, D, k) + Gs(cn, cd, p, D, k - 1)


def check_int(m, p, q, B, cn=1, cd=1):
    D = N * q
    X = sum(x * x for x in m)
    Y = 0
    for i in range(N):
        s = 0
        for j in range(N):
            s += m[j] * ks(cn, cd, p, D, i - j)
        Y += m[i] * s
    S = sum(m)
    lhs = 10 ** 6 * (6 * p * D ** 2 * cd * X + Y)
    rhs = 6 * B * p ** 2 * D * cd * S ** 2
    return lhs <= rhs, Fr(10 ** 6 * (6 * p * D ** 2 * cd * X + Y), 6 * p ** 2 * D * cd * S ** 2)


HEADER = """/-
# Theorem 1.4(a), package V: certificate data for `prop:certH` (Proposition 9.24, column `p(β(κ))`)

Step heights (integers `m_i`, scale `10^9`, `n = 400` cells of `[-β/2, β/2]`) for `β = 3/2, 4/3, 5/4, 7/6,
12/11` (`κ = 1, 2, 3, 5, 10`), `C = 1`. This file is generated by `scripts/gen_hybrid_data.py`, which
re-runs exactly the procedure of the paper's ancillary script `anc/certify_hybrid.py` (float KKT solve,
symmetrise, round) and checks every inequality below in exact integer arithmetic before emitting this file. Nothing
about how the heights were found matters: any admissible window gives a lower bound for `p(β; F_C)`.

The kernel `ksB` and the check `certCheckB` are defined in `FamiliesH.V.CertDefs`: for `β = p/q` and
`D = 400q` (cell width `h = β/400 = p/D`), the certificate inequality with denominators cleared is
`10⁶(6pD²c_d·∑m_i² + ∑_{i,j} m_i m_j ksB(i−j)) ≤ 6Bp²Dc_d·(∑m_i)²`, i.e. `𝒬_{F_C} ≤ B/10⁶`.

All checks are `decide +kernel` (kernel evaluation; no `native_decide`).
-/
import FamiliesH.V.CertDefs

namespace Families.Hybrid.V.CertDataH

open Families.CertData
"""


def main():
    out_path = os.path.join(HERE, '..', 'FamiliesH', 'V', 'CertData.lean')
    if '--out' in sys.argv:
        out_path = sys.argv[sys.argv.index('--out') + 1]
    rows = []
    for name, kap, p, q, target in ROWS:
        beta = Fr(p, q)
        f, Qf, how = solve_float(float(beta), 1.0, N, 'C')
        fs = 0.5 * (f + f[::-1])
        m = [max(0, int(round(v * 10 ** 9))) for v in fs]
        m = [(a + b) // 2 for a, b in zip(m, m[::-1])]
        assert m == m[::-1] and min(m) >= 0 and len(m) == N
        Q = exact_Q(m, beta, Fr(1), N, 'C')
        B = 2 * 10 ** 6 - int(Fr(target) * 10 ** 6)
        ok_rat = Q <= Fr(B, 10 ** 6)
        ok_int, q1e6 = check_int(m, p, q, B)
        same = (q1e6 == 10 ** 6 * Q)
        print(f"{name} kappa={kap} beta={p}/{q} [{how}] exact p={float(2 - Q):.9f} target={target} B={B} "
              f"rational_ok={ok_rat} integer_ok={ok_int} formula_consistent={same}", flush=True)
        assert ok_rat and ok_int and same
        rows.append((name, kap, p, q, target, B, m))
    L = [HEADER]
    for name, kap, p, q, target, B, m in rows:
        L.append(f"/-- Step heights of the certificate for `κ = {kap}`, `β = {p}/{q}`, `C = 1`. -/")
        body = [", ".join(str(x) for x in m[i:i + 8]) for i in range(0, N, 8)]
        L.append(f"def ms{name} : List Int := [" + ",\n  ".join(body) + "]")
        L.append("")
    for name, kap, p, q, target, B, m in rows:
        D = N * q
        L.append(f"theorem ms{name}_length : ms{name}.length = 400 := by decide +kernel")
        L.append(f"theorem ms{name}_reverse : ms{name}.reverse = ms{name} := by decide +kernel")
        L.append(f"theorem ms{name}_nonneg : nonnegCheck ms{name} = true := by decide +kernel")
        L.append(f"theorem ms{name}_sum_pos : 0 < ms{name}.sum := by decide +kernel")
        L.append(f"/-- **Certificate `κ = {kap}`**: `𝒬_{{F_1}}(f) ≤ {B / 10 ** 6:.6f}`, "
                 f"i.e. `p({p}/{q}; F_1) ≥ {target}`. -/")
        L.append(f"theorem cert{name} : certCheckB {p} {D} 1 {B} ms{name} (kerListB 1 1 {p} {D}) = true := by\n"
                 f"  decide +kernel")
        L.append("")
    L.append("end Families.Hybrid.V.CertDataH")
    with open(out_path, 'w') as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {os.path.normpath(out_path)}")


if __name__ == '__main__':
    main()
